version: '3.8'

services:
  nginx:
    build:
      context: ./frontend 
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"  # Expose port 8080 for the frontend
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile.production
    ports:
      - "3001:3001"  # Expose backend port 3001
    networks:
      - app-network
    env_file:
      - .env.backend.docker
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: always
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Using bridge network for inter-service communication
