export const SOCKET_CONNECTED = "connect"
export const SOCKET_DISCONNECTED = "disconnect"
export const SOCKET_CONNECTION_ERROR = "connect_error"
export const USER_CAME_ONLINE = "some_user_came_online"
export const ONLINE_STATUS_BROADCAST_FROM_SERVER = "user_sockets_status_broadcast"