name: Testing the code
on:
  push:
    branches:
      - release
jobs:
    build-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Installing dependencies
              run: |
                cd backend
                npm ci
            - name: Build backend
              run: |
                echo "switching to backend directory"
                cd backend
                npm run build
            - name: Set up Docker Compose
              run: sudo apt-get install docker-compose -y
            - name: Start services with Docker Compose
              run: docker-compose -f ./docker-compose.base.yml up -d --build
            # - name: Wait for containers to be healthy
            #   run: |
            #     docker-compose ps
            #     until [ "`docker inspect -f {{.State.Health.Status}} backend`" == "healthy" ]; do
            #       echo "Waiting for backend to be healthy..." 
            #       sleep 5
            #     done
            - name: Run tests in Node.js container
              run: docker-compose exec backend npm test
          
              # Tear down Docker Compose environment
            - name: Stop and remove containers
              if: success() || failure()
              run: docker-compose -f docker-compose.base.yml down
            