name: Testing the code
on: #workflow_dispatch
  push:
    branches:
      - release
  # workflow_dispatch
  
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: |
          cd frontend
          npm ci
      - name: Build frontend
        run: |
          echo "switching to frontend directory"
          cd frontend
          npm run build


  build-backend:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: |
          cd backend
          npm ci
      - name: Build backend
        run: |
          echo "switching to backend directory"
          cd backend
          npm run build
      - name: Test backend
        run: |
          echo "switching to backend directory"
          cd backend
          npm run test
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          PORT: ${{ secrets.PORT }}
          OPEN_CAGE_API_KEY: ${{ secrets.OPEN_CAGE_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
          JWT_COOKIE_EXPIRE: ${{ secrets.JWT_COOKIE_EXPIRE }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          ALLOWED_FRONTEND: ${{ secrets.ALLOWED_FRONTEND }}

  build-and-push-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKERHUB_NAMESPACE: 'shamsul070'
          IMAGE_NAME: 'chat-backend'
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
