name: Testing the code
on: 
  push:
    branches:
      - release
  workflow_dispatch:
  
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: |
          cd frontend
          npm ci
      - name: Build frontend
        run: |
          echo "switching to frontend directory"
          cd frontend
          npm run build


  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: |
          cd backend
          npm ci
      - name: Build backend
        run: |
          echo "switching to backend directory"
          cd backend
          npm run build
      - name: Test backend
        run: |
          echo "switching to backend directory"
          cd backend
          npm run test
      


