name: Testing the code
on: 
  push:
    branches:
      - release
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        run: |
          echo "switching to frontend directory"
          cd frontend
          npm run build
      - name: Build backend
        run: |
          echo "switching to the backend directory"
          cd backend
          npm run build

